### ISSUE TITLE
[BUG] Launching SteamVR creates a seemingly un-killable blank window [1.26.1]

### ISSUE THREAD

**Issue by Nervyalloy5** [ValveSoftware/SteamVR-for-Linux#577]
**Describe the bug**
When SteamVR is launched it spawns two windows: 
    -The settings menu (which functions normally, and is closable with no issues)
    -A blank window labled "Unknown" that is roughly the same size as the settings window

The blank window is seemingly impossible to close without re-logging into the desktop.

The x button on the titlebar is un-clickable, pressing the x button on the activities view does nothing, even xkill fails to close it.
I can't seem to find any process attached to the window, closing all Steam/SteamVR processes does not close them.

Loading SteamVR again simply spawns a duplicate of the window and the original is not affected.

Opening the desktop settings menu through the hamburger menu on the VRmonitor opens both the (once again functionall) settings menu and another blank window, Though the window labels are now switched (Blank window is "SteamVR Settings" and settings is "Unknown").

**To Reproduce**
1. Switch to the SteamVR Beta Update
2. Open SteamVR
3. Optionally open the settings menu again and spawn another window

**Expected behavior**
SteamVR should not spawn an un-killable window.

**System Information**
- Distribution: Arch Linux
- Desktop Environment: Gnome 43.4 (X11)
- SteamVR version: 1.26.1
- Steam client version:  Mar 24 2023 17:20:43
- Opted into Steam client beta?: No
- Graphics driver version:  Mesa 23.0.2
- Gist for SteamVR System Information: https://gist.github.com/nervyalloy51/11f9950b9b18c8f21b9850689f054dfa

**Screenshots**
Initial Launch:
![image](https://user-images.githubusercontent.com/24869676/230755355-c7d0aa7a-a9de-49d2-9cb6-d5469c2833bf.png)

Opening Settings Manually.
![image](https://user-images.githubusercontent.com/24869676/230755538-09292f09-6217-4913-aa08-7b8bf17fa337.png)

After A few Launches:
![image](https://user-images.githubusercontent.com/24869676/230755620-f72410fa-2ff9-447d-b656-cd90fa50970b.png)

**Additional context**
I am also affected by https://github.com/ValveSoftware/SteamVR-for-Linux/issues/572
though im not sure if the issues are related.

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by ZarathustraDK** [comment]
Experiencing the same problem here, both on KDE (Arch) and Gnome (Nobara)

System Information

-     Distribution: Nobara Project
-     Desktop Environment: Gnome 43.2-1.fc37 (X11)
-     SteamVR version: Beta 1.26.1
-     Steam client version: Mar 24 2023 17:20:43
-     Opted into Steam client beta?: No
-     Graphics driver version: Mesa 23.0.1-2.fc37
-     [Gist for SteamVR System Information](https://gist.github.com/ZarathustraDK/73b807800e959e5e9789cb8351a297fb)

**Comment by Patola** [comment]
A possible workaround:
`xdotool selectwindow windowunmap ; xdotool selectwindow windowunmap`
click on the window. it will become a grey square. click on it again. It will disappear.

**Comment by amalon** [comment]
Yeh, I've just been doing Ctl+Alt+Esc and click on it to get rid of it

**Comment by ClearlyClaire** [comment]
Same thing here with gnome 43.6

**System Information:**

- Distribution: Debian testing
- SteamVR version: 1.26.5
- Steam client version: 1688685284
- Opted into Steam client beta?: Yes
- Graphics driver version: Mesa 22.3.6
- Gist for SteamVR System Information: https://gist.github.com/ClearlyClaire/4140a24c026a9655db87e01814210f44

**Comment by mtfurlan** [comment]
`xdotool selectwindow windowunmap` made it look like I minimized the window, but I couldn't open it again.
I eventually killed all of them by doing `xwininfo` and `xkill -id $whateverID` at one of them.
This doesn't happen *every* time I open steamvr, just 4/5 times.

System Information:

- Distribution: Debian bookworm
- SteamVR version: 1.26.5
- Steam client version: 1687386907
- Opted into Steam client beta?: No
- Graphics driver version: nvidia 525.105.17
- Gist for SteamVR System Information: https://gist.github.com/mtfurlan/7825f4e4d17652863a22788cb20931f4

**Comment by SentineI** [comment]
Same here with Gnome 42.9 but it used to work fine.

System Information:
* Distribution: Ubuntu LTS 22.04.2
* SteamVR version: 1.26.6
* Steam client version: 1689034492
* Opted into Steam client beta?: No
* Graphics driver version: NVidia 535.54.03
* Gist for SteamVR System Information: https://gist.github.com/SentineI/3077ef8858ef018cbab04b5199bfa5d1

**Comment by MalikuMane** [comment]
In ~.steam/steam/config/steamvr.vrsettings, remove the entry with no title in the DesktopUI section to get rid of it.

**Comment by Patola** [comment]
> In ~.steam/steam/config/steamvr.vrsettings, remove the entry with no title in the DesktopUI section to get rid of it.

What if there's no entry with no title? My DesktopUI section is like that:
```
    2    "DesktopUI" : {                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
    3       "controllerbinding_desktop" : "737,130,1915,1075,0",
    4       "pairing" : "1320,420,799,599,0",
    5       "settings_desktop" : "1995,481,799,599,0"
    6    },

```

And I got the dreaded unkillable blank window.

**Comment by MalikuMane** [comment]
That's what i did to fix it for me, try clearing the controllerbinding_desktop one. I only have pairing and settings_desktop, those 2 just come back for me.

**Comment by MalikuMane** [comment]
Okay i got it this time. ~.local/share/Steam/steamapps/common/SteamVR/resources/webhelperoverlays.json set `"preload": false` in the `settings_desktop` section.

**Comment by DASPRiD** [comment]
That does get rid of the settings window starting up, though the blank unkillable window still comes up.

**Comment by MalikuMane** [comment]
Okay, tried it several times last night and it was gone. It came back this morning! `DesktopUI` in the `steamvr.vrsettings` is a saved list of windows to reopen. Clear this array. The blank one is `pairing`. The `preload` options in the `webhelperoverlays.json` files appear to mean always open on launch. Idk why anyone would want this ever!

The `pairing` window comes from:
`~.local/share/Steam/steamapps/common/SteamVR/drivers/lighthouse/resources/webhelperoverlays.json`
and `settings_desktop`:
`.local/share/Steam/steamapps/common/SteamVR/resources/webhelperoverlays.json`
`vrlink_pairing`:
`.local/share/Steam/steamapps/common/SteamVR/drivers/vrlink/resources/webhelperoverlays.json`

Set `preload` false for all just be sure. I launched several times and it still did not come back today!  @kisak-valve

**Comment by ClearlyClaire** [comment]
I can confirm that setting `preload` to `false` in all the aforementioned files. Opening the settings opens two windows: one without title but showing the settings, and a blank window with “SteamVR Settings”. Both can be closed, and are closed when SteamVR exits.

**Comment by Hicks79** [comment]
Hi 
me too
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/646#issuecomment-1837144139

**Comment by ZarathustraDK** [comment]
Confirmed. Clearing the DesktopUI-section of stuff in steamv.vrsettings and setting preload to false on the three files got rid of the black window.

Why it got there in the first place is strange though. I distinctly remember not having the problem on first runs/new installs. Perhaps the settings window needs to be accessed manually from the desktop first --> something bugs out --> now you can't get rid of because the window is never closed properly so SteamVR is effectively remembers it in perpetuity.

I suppose if it was working as intended, Steamvr would remember your open settings-window and respawn it on next run, but stop spawning it on new runs if you manage to close it correctly.

**Comment by founta** [comment]
Thanks! Setting preload false in those three files did the trick for me. It looks like changes to those files get wiped out if you eg switch to the steamvr beta branch, so maybe they will also get wiped when steamvr updates. I've been running this:
```
sed -ri 's/"preload"(.*)true/"preload"\1false/g' $HOME/.steam/steam/steamapps/common/SteamVR/drivers/lighthouse/resources/webhelperoverlays.json
sed -ri 's/"preload"(.*)true/"preload"\1false/g' $HOME/.steam/steam/steamapps/common/SteamVR/resources/webhelperoverlays.json
sed -ri 's/"_preload"(.*)true/"_preload"\1false/g' $HOME/.steam/steam/steamapps/common/SteamVR/drivers/vrlink/resources/webhelperoverlays.json
```

**Comment by SentineI** [comment]
Great, thanks for the fix!  For what it's worth, I'm using this slightly shortened script:
```
sed -ri 's/("preload".*)true/\1false/g' ~/.steam/steam/steamapps/common/SteamVR/drivers/lighthouse/resources/webhelperoverlays.json
sed -ri 's/("preload".*)true/\1false/g' ~/.steam/steam/steamapps/common/SteamVR/resources/webhelperoverlays.json
#sed -ri 's/("_preload".*)true/\1false/g' ~/.steam/steam/steamapps/common/SteamVR/drivers/vrlink/resources/webhelperoverlays.json
```
The last line is commented-out, as currently it doesn't seem to be necessary (but YMMV).

**Comment by rdeforest** [comment]
Changing the preload setting prevented the settings window from coming up when I start SteamVR, but now when I go to settings via the hamburger menu in the small window on the desktop, it still creates both windows AND I can't make the blank one go away. Seems like something is preventing the two windows from being one fully functional window.

**Comment by FathomRaven** [comment]
Same issue for me on Linux Mint 21.3. Followed the same instructions to get rid of the blank window, but now the settings one has to be manually opened, which makes the ghost window appear too.

**Comment by Patola** [comment]
I have the same issue when I try to go to SteamVR settings. I get two windows and it eventually crashes.

**Comment by rdeforest** [comment]
This may not be much help since I can't isolate what the relevant change is, but my symptoms are now that the dead window only sticks around the second or third time I start up SteamVR. After a clean reboot the window closes correctly. Renaming my settings file kept the window from opening up in the first place, but once I invoked the settings menu to bring the window back manually the problem was back.

Other changes I've made should be unrelated, but who knows: updated to all the latest packages again, installed mldonkey-server from oldoldstable, poked around to get my headphones to work with bluetooth, poked around to get sound working in the HMD.

I'll keep watching this thread so I can help verify a work-around if someone comes up with something that sticks and is repeatable.

**Comment by PhilT** [comment]
I was getting this same issue on NixOS unstable/dwm but after a SteamVR update my Steam library window disappears as well!

**Comment by tobico** [comment]
I'm seeing the same issue, running PopOS, with Nvidia GPU.

**Comment by ehwelbon** [comment]
I am seeing this on Ubuntu 22.04.4 LTS,   It happens mostly when the SteamVR fails to start, or is restarted, it leaves a dead window:

![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/37788500/f0929dd9-f7c4-4028-92f1-6e6c8dcbfd04)

If I run the following command, I can see a BadWindow indicated that I am confident it is at issue:
```
$ xprop -root _NET_CLIENT_LIST | pcregrep -o1 '# (.*)' | sed 's/, /\n/g' | xargs -I{} -n1 xprop -id {} _NET_WM_NAME
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x6200004
  Serial number of failed request:  13
  Current serial number in output stream:  13
  ...
  
``
So far, nothing short of restarting the xserver or rebooting will kill the window.  I tried the work-around of setting preload to false which seems to help somewhat, but I'll need to see an error condition occur to be sure.  

Comment: This dead window issue should be fixed.   Getting Linux SteamVR to start and run most games, is already fiddly, having additional hurdles such as this (or to get reliable mirrored audio etc.) is not going to endear Linux SteamVR to anyone that is not extremely persistent and/or proficient.  Most people (even Linux Support Techs), conclude after one failed attempt with Linux SteamVR that it either doesn't work or isn't worth the effort.  While that's not my view at all (I use VR on Linux much more often than Windows) that is what I hear when I try to evangelize the platform to my fundamentally tech compatriots.

**Comment by Boyfinn** [comment]
This also occurs to me with Linux Mint 21.3. It also creates a new black window if i open the settings menu. Doing this opens 2 windows, first the settings windows(which works fine), and then one of these blank unkillable windows alongside it. Closing the settings window has no effect on the second blank window.

**Comment by ehwelbon** [comment]
Try this workaround, it has worked for me: 
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/577#issuecomment-1872245424
or this one which is equivalent (somewhat shorter).
https://github.com/ValveSoftware/SteamVR-for-Linux/issues/577#issuecomment-1872400869
No more dead/black windows from SteamVR on Ubuntu 22.04 (I tried a few days ago).  I haven't yet updated to latest LTS version.

**Comment by mtfurlan** [comment]
Still have the issue, but less often than in the past

This script has has been helpful to me for the past year, just be very careful to click on the window you want to kill and not something else
```bash
#!/bin/bash
# https://github.com/ValveSoftware/SteamVR-for-Linux/issues/577#issuecomment-1627614326
read -r -p "gonna kill something, cool [y/N] " response
case "$response" in
  [yY][eE][sS]|[yY]|'')
      xkill -id "$(xwininfo | sed -n 's/xwininfo: Window id: \([^ ]*\).*/\1/p')"
    ;;
esac
```

**Comment by Entrix22** [comment]
I get the same. It just doesn't go away unless I do a reboot.

**Comment by Voxny404** [comment]
Same here! Pressing Alt + F2, typing r, and hitting Enter did the trick for me. It restarts the GNOME Shell (window manager) without needing to log out, and the issue was resolved instantly on Pop!_OS 22.04 LTS.

**Comment by KisaragiEffective** [comment]
> Pressing Alt + F2, typing r, and hitting Enter did the trick for me. It restarts the GNOME Shell (window manager) without needing to log out

This is DE-dependant

**Comment by Voxny404** [comment]
> 
> This is DE-dependant

This could work, but it's not guaranteed to work across all desktop environments (DEs)
`pkill -HUP -f 'gnome-shell|kwin|xfwm4|metacity|openbox|i3|sway'`

**Comment by Spacefish** [comment]
I have the problem as well...

My `DesktopUI` section in `steamvr.vrsettings`
looks like this:

```
 "DesktopUI" : {
      "" : "880,607,799,599,0",
      "T�\u0005��3" : "596,466,593,793,0",
      "debugcommands_desktop" : "260,615,920,788,1",
      "pairing" : "880,420,799,599,0",
      "settings_desktop" : "803,614,799,599,0",
      "t��E\u001C7" : "354,268,599,799,0"
   },
```

i removed it, and steam re-created the file with only a "pairing" and "settings_desktop" window?

The only thing that changed: The "ghost windows" created now have an "Arma: Cold War Assault Mac/Linux" title as well as the games logo..
Before it alway was "Firewall" and had the KDE Firewall settings logo

I have this game in my library, but it´s not the first in the list actually "Aerofly FS 1 Flight Simulator" ist the first. And it´s not even installed / i never had it installed..

Sounds really wierd to me.. The window seems to have some random app logo and matching title, but as "Firewall" + the Logo is from my OS and not even from steam, i guess that´s just random?

"Firewall" window
![Image](https://github.com/user-attachments/assets/9f2e713a-e996-4e4e-9bf7-e4f34341f68a)

"Arma" window
![Image](https://github.com/user-attachments/assets/cfd75350-0ad7-4e9d-90a4-396d8ab468cb)

b.t.w. would be really cool if SteamVR and the Steamclient itself uses Wayland instead of X in the future. One can dream :)

**Comment by meenphie** [comment]
we can soon celebrate this issue being 2 years old, yay!

**Comment by Spacefish** [comment]
> we can soon celebrate this issue being 2 years old, yay!

Yeah, but it´s probably a pain in the B... to fix it, as it´s probably caused by libcef (the embeeded chromium browser engine), which does not use Wayland but rather X11 under the hood.. That´s emulated in XWayland in a Wayland session.

As they probably redirect the Framebuffer(s) of the Browser Window(s) to show them in their VM compositor the "X11" window is left.
As the `Xwayland` process is the one connected to Wayland, the window just stays, even if SteamVR is closed.
doing a `killall Xwayland` removes the window, but that closes all applications using the emulated X11 server as well (not much nowerdays).

B.t.w. that´s the reason why "Desktop" in VR doesn´t work as well if you are in a Wayland based Session, SteamVR talks X11 and the backward compability X Server does not see the Desktop or any other Windows than X11 Windows.

**Comment by mtfurlan** [comment]
Given that this happens on systems without wayland installed, I don't think it's caused by xwayland

**Comment by dx9s** [comment]
I never had this issue, setup a newerish machine with Mint / Cinnamon and it it happening for me. Mint comes with some System Report / Crash Reports thing with entries for two programs (vrwebhlper and vrmonitor).. I poked LDD at the binaries and they are missing some:

~/.steam/debian-installation/steamapps/common/SteamVR/bin/vrwebhelper/linux64$ ldd vrwebhelper |grep "not found"
	libopenvr_api.so => not found
	libcef.so => not found
	libsteam_api.so => not found


~/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64$ ldd vrmonitor |grep "not found"
	libsteam_api.so => not found
	libopenvr_api.so => not found
	libnrfserlib.so => not found
	libQt5OpenGL.so.5 => not found
	libQt5Multimedia.so.5 => not found
	libQt5PrintSupport.so.5 => not found


I think finding the libs for these MIGHT solve it, but not sure. Will poke around. Not sure where to find all of them tho.

**Comment by dx9s** [comment]
Getting closer.. Firstly, understanding how /etc/ld.so.conf.d/ helps.. created an entry for steam64:
```
/etc/ld.so.conf.d$ cat steam64.conf 
# Manually Installed steam libs
/usr/local/lib/steam64
```

Then I copied the everything from /home/[home]/.steam/debian-installation/ubuntu12_64/ into it and reran ldconfig
``` 
~/.steam/debian-installation/steamapps/common/SteamVR/bin/vrwebhelper/linux64$ ldd vrwebhelper | grep "not found"
	libsteam_api.so => not found
```

Think that the linux installer could put all the libs they create and make it global via same method that would work WELL across any modern distro. I am still putting files into it (libsteam_api.so) for vrwebhelper

also vrmonitor: (after installing some apt install libqt5
``` 
sudo apt install libqt5printsupport5 libqt5printsupport5t64 
sudo apt install libqt5multimedia*
sudo apt install libqt5opengl5
...
:~/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64$ ldd vrmonitor | grep "not found"
	libsteam_api.so => not found
	libnrfserlib.so => not found
```
libsteam_api.so and nrfserlib.so are also someplace under ~/.steam I think and will manually copy over to /usr/local/lib/steam64

(writing this up while poking around so this MIGHT help, not sure ultimately)

**Comment by dx9s** [comment]
Didn't solve the window issue, and crash logs thing still catching vrwebhelper even after creating a local lib for steam64

**Comment by wallcarpet40** [comment]
Latest beta version of SteamVR (2.10.2) seems to fix the unkillable windows, at least on Fedora 41.

**Comment by YoshiRulz** [comment]
Seems to have fixed itself on my machine too. SteamVR is now version 2.9.6 (1738793859), Steam client 1743554648, Ubuntu 22.04.

edit: I don't know what to tell you, I'm definitely not using the beta.

**Comment by DASPRiD** [comment]
> Seems to have fixed itself on my machine too. SteamVR is now version 2.9.6, Steam client 1743554648, Ubuntu 22.04.

I still experience it on 2.9.6 :)

**Comment by jarettmillard** [comment]
> > Seems to have fixed itself on my machine too. SteamVR is now version 2.9.6, Steam client 1743554648, Ubuntu 22.04.
> 
> I still experience it on 2.9.6 :)

Yes, because it is fixed in 2.10.2, not 2.9.6: https://steamcommunity.com/games/250820/announcements/detail/505073176264311093

**Comment by Spacefish** [comment]
> edit: I don't know what to tell you, I'm definitely not using the beta.

It wasn´t 100% reproducable, i sometimes didn´t have the extra window, but sometimes had it, even before the patch.
Now it´s reliably gone and i as well don´t see the issue anymore, where one of the Windows stays black (like the settings).

Thanks for fixing it, unkown Valve Employee 👍🏻, and thanks for supporting VR on Linux!

**Comment by meenphie** [comment]
> Replying to https://github.com/ValveSoftware/SteamVR-for-Linux/issues/577#issuecomment-2767435202

I dont think thats correct because:

1. I dont use wayland
2. "Desktop" in VR dosn't work in X11 either

**Comment by HungryHedgehog** [comment]
Still happens under Linux Mint, xkill doesnt work on them either. It happens every time the settings window opens, which seemingly happens at launch too.

**Comment by Patola** [comment]
> Still happens under Linux Mint, xkill doesnt work on them either. It happens every time the settings window opens, which seemingly happens at launch too.

Under Wayland or Xorg? Which desktop environment?
Also, are you using SteamVR beta 20.10.2 and not SteamVR stable?

**Comment by 12bitmisfit** [comment]
I have this issue also using linux mint and steam installed from the .deb with cinnamon which is x11 not wayland. Running a 4080 with nvidia-550 drivers.

**Comment by Spacefish** [comment]
> I have this issue also using linux mint and steam installed from the .deb with cinnamon which is x11 not wayland. Running a 4080 with nvidia-550 drivers.

Are you using the "beta" branch of SteamVR or the Stable? It´s only fixed in the beta right now!

**Comment by dx9s** [comment]
> Are you using the "beta" branch of SteamVR or the Stable? It´s only fixed in the beta right now!

For myself, think I'm on stable -- I'll also check out Beta and report back!

**Comment by dx9s** [comment]
Okay, that seems to have solved that problem. Still has minor cosmetics (Restart SteamVR when changing settings for example, mouse pointer glitching when "viewing" the desktop from within VR, etc.) that can be worked around.

**Comment by kisak-valve** [comment]
Closing as fixed in SteamVR 2.10.2.
