### ISSUE TITLE
SteamVR Beta 2.0.3 through 2.4.1 Fails to connect to Window Manager

### ISSUE THREAD

**Issue by Esras** [ValveSoftware/SteamVR-for-Linux#622]
**Describe the bug**
SteamVR "Failed to connect to window manager (497)" on KDE Plasma (Wayland).

**To Reproduce**
- Log in to desktop environment
- Start SteamVR via the icon in the upper right

**Expected behavior**
SteamVR launches properly.

**System Information (please complete the following information):**
- Distribution: Fedora 39
- SteamVR version: 2.4.1
- Steam client version: 1709168962 
- Opted into Steam client beta?: Yes
- Graphics driver version: 550.54.14
- Gist for SteamVR System Information: https://gist.github.com/Esras/8b981184dc9594014e569060f90d4d64

**Additional context**
- There are also log messages in `journalctl` via `plasmashell`, but none of them seem particularly useful. Included as separate file in the gist.
- I see a core dump from vrwebhelper, but it seems to be after there's already a failure to connect. Stack trace in the gist.
<del>- The headset was rendering the pretty void (the one with the vague vaporwave feel to it) and could see the base stations as well as the boundaries that had been set awhile ago, but launching something failed to launch it in the headset.</del> Headset no longer shows anything on 2.3.3
- Headset shows the vaporwave background again on 2.4.1!

---

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by LandonDeam** [comment]
I believe I might be having the same or a similar issue. I'm getting a different error/code combo ("A key component of SteamVR isn't working correctly. Please reinstall SteamVR.", code 303), though perhaps it's because I'm on X11 and not Wayland, or because of the distro difference.

System Information
    Distribution: Arch Linux (Zen Kernel 6.5.5-1)
    SteamVR version: 2.0.3
    Steam client version: 1696019606
    Opted into Steam client beta?: No
    Graphics driver version: mesa 1:23.2.1-1
    Gist for SteamVR System Information: https://gist.github.com/LandonDeam/09d7b4d210063d3f72baa0f5882198bf

**Comment by caseif** [comment]
@LandonDeam My money would be on it being a separate issue, but I obviously could be wrong about that. In any event, I've created #623 to track it.

**Comment by TarsiSurdi** [comment]
I'm experiencing this same issue on Fedora 38 using Wayland + NVIDIA Drivers 535.113.01

### System Information

Computer Information:
Manufacturer: Micro-Star International Co., Ltd.
Model: B450M BAZOOKA (MS-7A38)
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Ryzen 5 2600X Six-Core Processor
CPU Family: 0x17
CPU Model: 0x8
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 3600 MHz
12 logical processors
6 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
Fedora Linux 38 (Workstation Edition) (64 bit)
Kernel Name: Linux
Kernel Version: 6.5.5-200.fc38.x86_64
X Server Vendor: The X.Org Foundation
X Server Release: 12201009
X Window Manager: GNOME Shell
Steam Runtime Version: steam-runtime_0.20230919.60656
Video Card:
Driver: NVIDIA Corporation NVIDIA GeForce RTX 2060/PCIe/SSE2
Driver Version: 4.6.0 NVIDIA 535.113.01
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 74 Hz
VendorID: 0x10de
DeviceID: 0x1f08
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 1920 x 1080
Desktop Resolution: 1920 x 1080
Primary Display Size: 20.87" x 11.81" (23.98" diag), 53.0cm x 30.0cm (60.9cm diag)
Primary VRAM: 6144 MB
Sound card:
Audio device: USB Mixer
Memory:
RAM: 15897 Mb
VR Hardware:
Headset: Oculus Miramar (oculus)
Miscellaneous:
UI Language: English
LANG: en_US.UTF-8
Total Hard Disk Space Available: 952246 MB
Largest Free Hard Disk Block: 316872 MB
Storage:
Number of SSDs: 3
SSD sizes: 2000G,1000G,1000G
Number of HDDs: 0
Number of removable drives: 0

**Comment by ThaSwapMeetPimp** [comment]
Having same issue (error 497) with beta 2.0.4 when using Steam Client Stable Channel on KDE Plasma (x11)

**Comment by TarsiSurdi** [comment]
Interesting... just tested beta 2.0.4 and I still got the same error messages and no SteamVR Home. Launching a game (Beat Saber) is successful but the game is displayed on the PC's screen only; on the headset it's just a black void.

![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/19439765/81282dd5-74f0-4b5b-b369-b9d69d882609)

**Comment by jarettmillard** [comment]
I'm getting the same thing with the Steam VR beta 2.0.5, Pop OS 22.04, Steam client stable, Gnome/X11, Nvidia card with driver 535.113.01. I'm also using ALVR.

**Comment by Limpooka** [comment]
I'm on Pop!_OS with Valve Index and AMD, and I can't get SteamVR to start any more.  
Tried with 2.0.6 and got the window manager error.  Rolled back to 1.27.5 and I'm still getting the window manager error.

Basically can't use SteamVR now.

**Comment by TarsiSurdi** [comment]
> I'm on Pop!_OS with Valve Index and AMD, and I can't get SteamVR to start any more.  
> 
> Tried with 2.0.6 and got the window manager error.  Rolled back to 1.27.5 and I'm still getting the window manager error.
> 
> 
> 
> Basically can't use SteamVR now.

I still cannot get the 2.0.6 beta to connect to the window manager, however, when downgrading from it the the stable version (1.27.5) gets SteamVR to work as intended and connect to the headset ONCE. After exiting the app, however the entire Steam (beta) Client crashes and upon opening it again SteamVR has an ~500Mb update to be done. After applying this specific update, SteamVR is completely borked again. Seems like there's something weird going on with the way Steam is handling SteamVR's depots when downgrading or something... 🤔

Installing the stable / beta channels from scratch (full uninstall) yields different results:
- Stable: launches but cannot get past window manager connection;
- Beta: doesn't even launch;

It' really weird but the only instance in which I managed to get VR to work on my setup (once) is to downgrade from beta to stable like this...

**Comment by ThaSwapMeetPimp** [comment]
Alright, after replacing vrsetup.sh with the updated script from #618, getting error 497 on SteamVR Beta 2.0.6 on Beta Channel, however I have vr space and Library access, am able to launch Contractors VR, exit out and Home comes up. This time consistently across two attempts. Going to reboot and see if it still works, check a couple other games.

**Comment by ThaSwapMeetPimp** [comment]
Alright, after replacing vrsetup.sh with the updated script from #618, getting error 497 on SteamVR Beta 2.0.6 on Beta Channel, however I have vr space and Library access, am able to launch Contractors VR, exit out and Home comes up. This time consistently across two attempts. Going to reboot and see if it still works, check a couple of other games.

**Comment by josh4364** [comment]
Running into this with SteamVR Beta 2.0.8, Also getting left behind vrwebhelper windows when closing and opening steamvr, beta or normal.
Trimmed system info:
```
System:
  Kernel: 5.15.0-87-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 5.6.8
    tk: GTK 3.24.33 wm: muffin dm: GDM3, LightDM Distro: Linux Mint 21.1 Vera
    base: Ubuntu 22.04 jammy
CPU:
  Info: 24-core (8-mt/16-st) model: 13th Gen Intel Core i9-13900K bits: 64 type: MST AMCP
Graphics:
  Device-1: NVIDIA GA102 [GeForce RTX 3090] driver: nvidia v: 535.113.01
  Screen-1: 0 s-res: 3840x2160 s-dpi: 60
  Monitor-1: HDMI-0 res: 3840x2160 dpi: 61 diag: 1836mm (72.3")
  OpenGL: renderer: NVIDIA GeForce RTX 3090/PCIe/SSE2 v: 4.6.0 NVIDIA 535.113.01
    direct render: Yes

```

**Comment by JupiterSky11** [comment]
SteamVR Beta 2.0.8, beta Steam client.  Having the same issue, alongside a black window that is un-killable.  Also, the microphone isn't activating but that might be a separate issue.

```
System:
  Host: MAIN-NODE Kernel: 6.2.0-33-generic x86_64 bits: 64
    Desktop: GNOME 42.9 Distro: Ubuntu 22.04.3 LTS (Jammy Jellyfish)
CPU:
  Info: 8-core model: Intel Core i7-9700K bits: 64 type: MCP cache: L2: 2 MiB
  Speed (MHz): avg: 4600 min/max: 800/4900 cores: 1: 4600 2: 4600 3: 4601
    4: 4601 5: 4600 6: 4600 7: 4600 8: 4600
Graphics:
  Device-1: NVIDIA GA102 [GeForce RTX 3080] driver: nvidia v: 535.113.01
  Display: server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia
    unloaded: fbdev,modesetting,nouveau,vesa gpu: nvidia resolution: 2560x1440
  OpenGL: renderer: NVIDIA GeForce RTX 3080/PCIe/SSE2
    v: 4.6.0 NVIDIA 535.113.01
```

**Comment by ThaSwapMeetPimp** [comment]
Steam Beta 2.0.8, Client Beta: Failed to connect to Window Manager error 497.  Exits cleanly after error 497. Upon SteamVR restart (ONLY from the link in the window telling you you may need to restart SteamVR, as it does not work if you exit from Client Beta entry or restarting Client Beta, or rebooting the computer) get the other error (303). Going to other error thread.

**Comment by megagtrwrath** [comment]
I've found a temporary workaround for this. I can get past this by 
1: Turn off SteamVR
2: unplugging the headset
3: Plugging in the headset
4: Start SteamVR
5: Repeat until video in headset.

Tested with Index headset, with Nvidia Drivers on KDE with Wayland on. 

If this works for you and you don't have either, do create a comment.

When it doesn't work, by doing xrandr it shows an xwayland display as disconnected. This will stack until you reboot the system.

Distribution: Arch [KDE Wayland]
SteamVR version: 2.0.8 (Stable)
Steam client version: 1698260427
Opted into Steam client beta?: Yes
Graphics driver version: 545.23.06
Gist for SteamVR System Information: https://gist.github.com/megagtrwrath/f72135dc0435c4f515678d35d33d62e8

**Comment by extraymond** [comment]
Using native runtime instead of steam runtime allows me to bypass this error and face the 303 instead, but at least it's working.

**system setup**:
os: ubuntu 22.04
desktop environment: kde plasma 5.27(x11)
steam: steam beta (official deb)
notable ppas:
  - kubuntu-ppa/backports-extra
  - kisak/kisak-mesa
gpu: amdgpu rx6800

**reproduction**:
- instead dependencies for i386 packages using the command [here](https://wiki.archlinux.org/title/Steam/Troubleshooting#Finding_missing_game_libraries)
- launch steam without steam runtime `STEAM_RUNTIME=0 steam`
- able to start steamvr without facing "Fails to connect to Window Manager"
- able to launch app from within

**observations**:
- while using steamvr-beta 2.0.8 with steam-beta, it's still showing the old UI, and some features are not working:
  - showing desktop is not working
  - clicking on store not working
  - clicking on library not working
  - recenter/open settings work
  - close steamvr works

**Comment by JupiterSky11** [comment]
Here's the relevant part of my vrcompositor.txt log if anyone's interested.  All it really says is that it can't do the thing, which we already know to be the case.  No other logs have any information regarding any errors.
```
Thu Oct 26 2023 18:34:03.234428 [Info] - Async support disabled by user setting
Thu Oct 26 2023 18:34:03.281222 [Info] - m_pVkInstance : 0x5644b2d213a0
Thu Oct 26 2023 18:34:03.281266 [Info] - m_pVkPhysicalDevice : 0x5644b2df2ca0
Thu Oct 26 2023 18:34:03.281275 [Info] - m_pVkDevice : 0x5644b3171420
Thu Oct 26 2023 18:34:03.281283 [Info] - m_pVkGraphicsQueue : 0x5644b2dec390
Thu Oct 26 2023 18:34:03.281290 [Info] - m_pVkComputeQueue : (nil)
Thu Oct 26 2023 18:34:03.281302 [Info] - HMD swapchain mode:2 count:3
Thu Oct 26 2023 18:34:03.299534 [Info] - Direct mode: enabled
Thu Oct 26 2023 18:34:03.300075 [Error] - CHmdWindowSDL: Failed to initialize mirror window
Thu Oct 26 2023 18:34:03.300101 [Info] - Enabling GPU profiling! /home/jupitersky/.steam/debian-installation/steamapps/common/SteamVR/bin/linux64
Thu Oct 26 2023 18:34:03.300925 [Error] - Error making window!
Thu Oct 26 2023 18:34:03.310346 [Info] - Failed to kill gpu-trace
Thu Oct 26 2023 18:34:03.310490 [Info] - Failed to initialize compositor
Thu Oct 26 2023 18:34:03.310516 [Info] - Failed to start compositor: VRInitError_Compositor_CannotConnectToDisplayServer
```

**Comment by ThaSwapMeetPimp** [comment]
Ugh.....on 2.0.10, only getting error 497 now, and is unusable even when displaying vr space in the HMD as the dashboard is not showing up either. This probably should have been fixed first, as SteamVR is still usable with error 303.

**Comment by ThaSwapMeetPimp** [comment]
Seems to be fixed as of 2.1.1. Even getting the new UI, though red and blue channels are switched still.

**Comment by TarsiSurdi** [comment]
Can confirm SteamVR 2.0.10 is now working on Fedora 39 (545 NVIDIA drivers) even on GNOME Wayland, also tested KDE Plasma.

However, OpenXR applications aren't working, but that's another issue entirely.

**Comment by FlipperLP** [comment]
Same issue here. Version 2.0.10

**Comment by jon-bit** [comment]
fixed a bug a few days ago. Now I have this :(. looks the same as @sparker256

steam vr: 2.1.4
linux: jos linux (realy just slightly modified mint)
headset: HTC vive

**Comment by jon-bit** [comment]
Quick update: Flatpak steam works HOWEVER steam .deb file does not. I just wanted to let everyone know in case if it helps someone.

**Comment by twhitehead** [comment]
Quick heads up that I started getting this on and AMD GPU under X11 one day out of what seemed like the blue
![error](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/787843/eee5be0f-479e-4e87-b7b1-0aa22e98313c)
sometime I got this as well
![error2](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/787843/a553359e-be74-473b-813e-5bb86adc141a)
Seemed like the only thing I couldn't get was a working StreamVR. Even when I went back to versions I knew had worked before.

Finally traced it down. DRI3 had become disabled due to me having upgraded mesa without also upgrading the Xorg amdgpu driver. Relevant message in Xorg log file
```
...
Nov 27 19:02:26 tux xserver-wrapper[19514]: DRI driver not from this Mesa build ('23.1.9' vs '23.0.3')
Nov 27 19:02:26 tux xserver-wrapper[19514]: failed to bind extensions
...
[   132.209] (==) AMDGPU(0): DRI3 disabled
```
and `xdpyinfo` output
```
...
number of extensions:    27
..
    DPMS
    DRI2
    GLX    <-- DRI3 should follow DRI2
...
```

The reason it was so puzzling was the was a several day delay between when I upgraded the mesa drivers without upgrading amdgpu and when I logged out and back in, restarted Xorg, and triggering the loss of DRI3.

Now that I know what it is. It is totally reproducible. Make sure the mesa version agree, and everything works fine. Make them different, and it is all broken. Hope this info will help someone else.

**Comment by elijahsgh** [comment]
Happy New Year
Anyone figure this out?
Fedora 39. Beta doesn't work. Tried the suggested desktop environments (Xorg, Hyprland, Sway, ...), verified xrandr --verbose, cable works fine in windows, ...

**Comment by poVoq** [comment]
Fedora 39, KDE on Wayland.
Steam Beta 2.4.1
AMD RX7600

Same error still.

**Comment by elijahsgh** [comment]
> Fedora 39, KDE on Wayland. Steam Beta 2.4.1 (on stable it is the same) AMD RX7600
> 
> Same error still.

Yeah I don't think anyone is working on this or fixing it so we have a large Valve Index Paperweight. :(

**Comment by poVoq** [comment]
To me it looks like SteamVR 2.x regressed to trying to access the screen through Xorg, which even with Xwayland will fail.

It used to work fine on KDE with Wayland before though.

**Comment by Esras** [comment]
Please do not comment on the thread with complaints about the software in general. It both adds noise to the signal and is _very_ demoralizing, as someone who's worked on software before. If you have additional debugging information, please add it.

**Comment by elijahsgh** [comment]
> Please do not comment on the thread with complaints about the software in general. It both adds noise to the signal and is _very_ demoralizing, as someone who's worked on software before. If you have additional debugging information, please add it.

We've had no updates since November and I bumped it over a month ago. There have been no replies or responses.

Do you have any updates?

**Comment by Esras** [comment]
With the release of the 550.54.14 Nvidia driver, I checked all the logs again, and a bit of the signature of the bug has changed, so it's not clear if it's the same bug.

Steam reports a 109 ("SteamVR Fails to Initialize"), which I take as a more generic report back to Steam, and SteamVR still has the 497 error.

I'm seeing a coredump happening in `vrwebhelper`, in `libglib-2.0.so.0.6600.8 + 0x51e6b`, with a couple of what seem like relevant lines before it:

```
plasmashell[57246]: ../../third_party/tcmalloc/chromium/src/tcmalloc.cc:337] Attempt to free invalid pointer {address}
...
kernel: vrwebhelper[57246]: segfault at 39 ip 00007f7c49603824 sp 00007ffe003d77d0 error 6 in libcef.so[7f7c494ec000+7770000] likely on CPU 8 (core 8, socket 0)
```

The full new stack trace can be seen at: https://gist.github.com/Esras/9c76fe7e076082f0838c683cf08af113

Original message has updated Steam info.

**Comment by makinbacon21** [comment]
Hello! F40 beta, same issue. If I pull the old (1.14) tag it works but not only is it ancient but then games don't launch properly (if at all) and it's super buggy.

**Comment by makinbacon21** [comment]
Fun discovery! It does in fact work on X11. I guess I'll keep an XFCE install on here.

**Comment by elijahsgh** [comment]
How did you get it to work?
I tried hyprland, etc, gnome on x11, Wayland bridge, etc

**Comment by makinbacon21** [comment]
More updates! Seems to initialize properly using `AMD_VULKAN_ICD=RADV RADV_DEBUG=nodcc %command%`

**Comment by TobiasCGoetz** [comment]
Seems to be resolved for me on Fedora 40 KDE with SteamVR 2.5.4 now.

**Comment by poVoq** [comment]
Can confirm that the video out works again with Fedora 40 KDE on Wayland with SteamVR 2.5.4.

Thanks a lot for fixing this!

**Comment by kisak-valve** [comment]
Closing per "Fixed an SDL compatibility problem on Fedora." in the [SteamVR 2.5](https://store.steampowered.com/news/app/250820/view/4186735430669975751) update cycle.

**Comment by slxdy** [comment]
@kisak-valve Are you sure it's resolved?
![image](https://github.com/user-attachments/assets/c103d485-3450-4ad1-a9dc-0edcebc7b560)
Running on latest stable Kubuntu with Nvidia 560 drivers

**Comment by kisak-valve** [comment]
Hello @slxdy, please open a new issue report with logs for a SteamVR dev to ponder.
