### ISSUE TITLE
[BUG] SteamVR 2.0.3: Shared IPC Compositor Init Failed (303)

### ISSUE THREAD

**Issue by caseif** [ValveSoftware/SteamVR-for-Linux#623]
**Describe the bug**
SteamVR is reporting error 303 (Shared IPC Compositor Init Failed) on launch in a Plasma Wayland session. This was not occurring with 2.0.1 and does not occur while opted out of the SteamVR beta. It is unaffected by the Steam client version (beta vs. stable).

This is the same error that was occurring in #572. I was unable to test in a Plasma X11 session due to SteamVR failing to detect the headset display in that desktop environment.

**To Reproduce**
1. Opt into Steam client beta and SteamVR beta
2. Launch SteamVR
3. Steam reports "Shared IPC Compositor Init Failed (303)"

**Expected behavior**
The error should not occur.

**System Information (please complete the following information):**
- Distribution: Arch
- SteamVR version: 2.0.3
- Steam client version: 1696541351
- Opted into Steam client beta?: Yes
- Graphics driver version: 23.2.1
- Gist for SteamVR System Information: https://gist.github.com/caseif/07063f5f9f6abe209d199672cb7969b9

**Note:** Commenters who are also experiencing this issue are encouraged to include the "System Information" section in their replies.

**Comment by LandonDeam** [comment]
I found that this issue does not occur on 2.0.2 either. My assumption would be that the switch over to a different runtime for 2.0.3 would be causing some sort of havoc here, although that's just a guess.

**Comment by NewtSoup** [comment]
I get this in 2.03 but things seem to work anyway.  I am getting improved performance over 2.02 but some games are still unplayable due to Reprojection and CPU late starts ( orange and magenta lines respectively in the performance graph )

I have had to set my headset FPS to 80fps and then I get:
12-14ms / 12.5ms  Skyrim VR  - playable with maginal performance.

14-16ms / 12.5ms Fallout 4 VR - unplayable still due to reprojection 

These two games are my litmus test as they were both working very Acceptably in Steam VR 1.26.
Only with 1.27 and later did I suffer severe performance issues.
 
@LandonDeam I don't suppose you have instructions on how to roll back Steam VR do you?  I want to go back to 1.26 as the last working version for me.  I have had no VR gaming ability for over a month.

**Comment by LandonDeam** [comment]
> @LandonDeam I don't suppose you have instructions on how to roll back Steam VR do you? I want to go back to 1.26 as the last working version for me. I have had no VR gaming ability for over a month.

I'm not sure if 1.26 is in the beta or mainline. Either way, you can just use [Depot Downloader](https://github.com/SteamRE/DepotDownloader) and the [SteamVR SteamDB page](https://steamdb.info/app/250820/) to find the manifest of the update you want (though you might have to sign in). Then you can just copy+paste the files in the depot folder over the ones in the SteamVR folder in Steam (you can find it by right clicking on SteamVR in Steam > Properties > Installed Files > Browse).

**Comment by NewtSoup** [comment]
> > @LandonDeam I don't suppose you have instructions on how to roll back Steam VR do you? I want to go back to 1.26 as the last working version for me. I have had no VR gaming ability for over a month.
> 
> I'm not sure if 1.26 is in the beta or mainline. Either way, you can just use [Depot Downloader](https://github.com/SteamRE/DepotDownloader) and the [SteamVR SteamDB page](https://steamdb.info/app/250820/) to find the manifest of the update you want (though you might have to sign in). Then you can just copy+paste the files in the depot folder over the ones in the SteamVR folder in Steam (you can find it by right clicking on SteamVR in Steam > Properties > Installed Files > Browse).

Thank you thank you.   1.26 is mainline.

**Comment by sparker256** [comment]
I am seeing this with 2.0.5

[SteamVR-2023-10-12-AM_11_25_33.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/12884264/SteamVR-2023-10-12-AM_11_25_33.txt)

**Comment by PistolRcks** [comment]
Also seeing this with 2.0.5. Also, the new SteamVR dashboard does not display in this way.

Distribution: Manjaro Linux
SteamVR version: 2.0.5
Steam client version: 1697059308
Opted into Steam client beta?: Yes
Graphics driver version: 535.113.01 (Nvidia)
SteamVR System Information: [SteamVR-2023-10-13-PM_02_35_54.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/12898218/SteamVR-2023-10-13-PM_02_35_54.txt)

**Comment by sparker256** [comment]
Still with 2.0.6

![SteamVR_Beta_206_Settings](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/1274225/bd9918e6-ab01-4557-9663-a55ed259b0d0)

[SteamVR-2023-10-15-PM_07_40_29.txt](https://github.com/ValveSoftware/SteamVR-for-Linux/files/12910922/SteamVR-2023-10-15-PM_07_40_29.txt)

**Comment by LandonDeam** [comment]
I fixed my compositor not launching. The solution for me was to make a symlink at /home/user/.steam/root/ called ubuntu12_32 and link it to /home/user/.local/share/Steam/ubuntu12_32/. I was getting the error `/home/landon/.local/share/Steam/steamapps/common/SteamVR/bin/linux64/vrcompositor-launcher.sh: line 34: /home/landon/.steam/root/ubuntu12_32/steam-runtime/run.sh: No such file or directory` for reference. I don't have access to the new UI (or any UI for that matter), but I can at least launch the SteamVR beta with this. I'll keep digging into that specific issue to see if I can't find any fix/workaround for that as well. Hope this helps someone :)

**Comment by ThaSwapMeetPimp** [comment]
After applying the replacement vrsetup.sh script from #618, first got failure to connect to window manager, then after reboot, now getting error 303. Also still old UI, but none of the times I have gotten beta to launch have I gotten the new UI so not surprised.

**Comment by ClearlyClaire** [comment]
I have the same error message, but it does not seem to prevent SteamVR from actually working.

**Comment by ThaSwapMeetPimp** [comment]
SteamVR Beta 2.0.8, Beta Client: Only after relaunching using the link above the SteamVR window after error 497 (no other way restarting SteamVR, just goes back to error 497 any other way) , Steam restarts from error 497 Failed to Connect to Window Manager with error 303 Shared IPC Compositor Init Failed. Also is saying that Steams Beta Client is required, even though I am on Beta Client already.

**Comment by megagtrwrath** [comment]
Todays stable Steam VR 2.0.8 release still does not resolve this issue. I can manage to get error 497 to subside by restarting SteamVR and completely disconnecting the headset, then connecting it again before restarting SteamVR. Old UI still shows, and SteamVR shows an error stating the Steam client needs to be updated despite being on latest beta client.

System Information (please complete the following information):

Distribution: Arch
SteamVR version: 2.0.8 (Stable)
Steam client version: 1698260427
Opted into Steam client beta?: Yes
Graphics driver version: 545.23.06
Gist for SteamVR System Information: https://gist.github.com/megagtrwrath/f72135dc0435c4f515678d35d33d62e8

Included is images showing the problem
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/16152534/42ec909e-0ae8-4906-bb4f-606f638231c5)
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/16152534/cf96def8-a1c1-432b-bf06-4a20681089e5)
![image](https://github.com/ValveSoftware/SteamVR-for-Linux/assets/16152534/e589a1f1-fed8-489c-b37a-88fd5dbb795b)

**Comment by vermeeren** [comment]
With a recent Mesa and LLVM 16 (see above ref) all you get is a black screen, probably due to https://github.com/ValveSoftware/Dota-2/issues/2285#issuecomment-1520942742 and https://airlied.blogspot.com/2023/04/fedora-38-llvm-vs-team-fortress-2-tf2.html. The tcmalloc problems now affect Home, Alyx and with SteamVR 2 the base VR compositor/overlay itself, meaning VR cannot be used at all. (Debian trixie (testing) can easily reproduce this.)

Many other things are affected too, such as Dota https://github.com/ValveSoftware/Dota-2/issues/2285 and Source 1 games https://github.com/ValveSoftware/Source-1-Games/issues/5043.

cc @TTimo as I saw your recent work on #618.

---

**Edit before posting** Apparently I run into #616 instead, disabling `enableLinuxVulkanAsync` made it work, though the error 303 IPC init failed still pops up. Async worked perfectly with the previous SteamVR 1 release for games. (The compositor and steam overlay had rendering glitches, but the game itself it worked perfectly.) In SteamVR 2 the one time it booted with async (mixed mesa/llvm versions in memory) async worked perfect in Steam overlay/compositor but with severe blur/old-frame-merges/double-vision in the game itself.

All in quite confusing but I agree SteamVR 2 needs more work on Linux and it would be nice if there can be a Linux branch for the newest SteamVR 1 so we can continue to play without major issues.

**Comment by LandonDeam** [comment]
Had no idea this even made it to the main branch until I got like 15 emails from Github today lol. Valve definitely need to get working on this issue, and if it's just an LLVM incompatibility, fix it relatively soon. As was said earlier, TF2 was giving me some grief recently, but fixing that just amounted to dropping in a replacement library. Perhaps there's a similar solution here that we haven't yet discovered?

**Comment by 2-3-5-41** [comment]
This is happening on the stable release of SteamVR 2.0.8 that released today on Oct 25, 2025.

**Comment by vermeeren** [comment]
For those that want to revert to 1.27.5 (latest before SteamVR 2) I will write here how. Works with steam beta client, overlay works too but only basic features (not the old big picture UI parts). Async with `enableLinuxVulkanAsync` works too, unlike black screen #616 with new version.

1. Open Steam as normal.
2. Run `steam steam://open/console` in a terminal, this should add a `console` tab to Steam client on top, go there.
3. Download old OpenVR Linux `download_depot 250820 250823 6793017837429788461`, download can be very slow wait until it prints download complete.
4. Download old OpenVR Content `download_depot 250820 250824 2232945182712745816`, again wait.
5. Below commands (or do the same with a file manager), adjust paths matching your installation.

```bash
cd ~/.steam/debian-installation/steamapps/common/SteamVR/bin
rm -rf linux64
cp -a ~/.steam/debian-installation/ubuntu12_32/steamapps/content/app_250820/depot_250823/bin/linux64 .
rm -rf vrwebhelper
cp -a ~/.steam/debian-installation/ubuntu12_32/steamapps/content/app_250820/depot_250823/bin/vrwebhelper .

# don't delete here, add and overwrite only
cd ~/.steam/debian-installation/steamapps/common/SteamVR
cp -a ~/.steam/debian-installation/ubuntu12_32/steamapps/content/app_250820/depot_250824/resources .
```

This is a pretty hacky partial overwrite of the new version, but it works. You probably want to fully uninstall SteamVR and clean install it in the future to try new versions out.

**Comment by NewtSoup** [comment]
> For those that want to revert to 1.27.5 (latest before SteamVR 2) I will write here how. Works with steam beta client, overlay works too but only basic features (not the old big picture UI parts). Async with `enableLinuxVulkanAsync` works too, unlike black screen #616 with new version.
> 
> 1. Open Steam as normal.
> 2. Run `steam steam://open/console` in a terminal, this should add a `console` tab to Steam client on top, go there.
> 3. Download old OpenVR Linux `download_depot 250820 250823 6793017837429788461`, download can be very slow wait until it prints download complete.
> 4. Download old OpenVR Content `download_depot 250820 250824 2232945182712745816`, again wait.
> 5. Below commands (or do the same with a file manager), adjust paths matching your installation.
> 
> ```shell
> cd ~/.steam/debian-installation/steamapps/common/SteamVR/bin
> rm -rf linux64
> cp -a ~/.steam/debian-installation/ubuntu12_32/steamapps/content/app_250820/depot_250823/bin/linux64 .
> rm -rf vrwebhelper
> cp -a ~/.steam/debian-installation/ubuntu12_32/steamapps/content/app_250820/depot_250823/bin/vrwebhelper .
> 
> # don't delete here, add and overwrite only
> cd ~/.steam/debian-installation/steamapps/common/SteamVR
> cp -a ~/.steam/debian-installation/ubuntu12_32/steamapps/content/app_250820/depot_250824/resources .
> ```
> 
> This is a pretty hacky partial overwrite of the new version, but it works. You probably want to fully uninstall SteamVR and clean install it in the future to try new versions out. (Edit: Steam may complain about not finding HMD but it works anyway.)

Last usable version for me was 1.26, the 1.27release introduced a ton of cpu false starts that made VR look like drunk double vision slide show.  This continued into 2.xx for me.  I have not been able to play VR games since 1st Week September.

**Comment by CobaltSpace** [comment]
Use https://steamdb.info/app/250820/patchnotes/ to find the manifest ids for the update you want.

**Comment by vermeeren** [comment]
@NewtSoup In case you cannot (easily) find it in the patch notes posted above, as I think not every patch is actually on that page, you can also look at manifest history itself and copy the relevant manifest ID from the table based upon the date it was working.

* OpenVR Linux https://steamdb.info/depot/250823/manifests/
* OpenVR Content https://steamdb.info/depot/250824/manifests/

**Comment by Limpooka** [comment]
Just received the Steam client and SteamVR updates.  SteamVR  continues to have a number of problems, including all the ones found in 1.27.5.  I'm basically still unable to play games.  

List of issues includes:
1. Peculiar black window opening behind the SteamVR settings window, that persists after closing Steam.  Sometimes causes a total desktop freeze.
2. Insists on updating SteamVR to what I guess is proton - then fails to start because it can't find the SteamVR.exe.  I have to force "no-steam-play" with ProtonUp-Qt in order to get it to work.  This happens on EVERY boot.
3. No discernable difference in the UI from the previous version.
4. At 120hz, everything is a double-vision mess running in the orange at 10 of 8.3ms - in the VR Home default room.
5. 12. Controllers working in some games, but completely undetected in others
6. [logs] Unable to update Steam icon 
7. [logs] .steam/debian-installation/steamapps/common/SteamVR/bin/linux64/vrstartup: error while loading shared libraries: libopenvr_api.so: wrong ELF class: ELFCLASS32
8. [logs] ./vrwebhelper: error while loading shared libraries: libcef.so: cannot open shared object file: No such file or directory
9. [logs] Fossilize INFO: Overriding serialization path: ".steam/debian-installation/steamapps/shadercache/250820/fozpipelinesv6/steamapprun_pipeline_cache".
10. [logs] Fontconfig warning: ".steam/debian-installation/steamapps/common/SteamVR/tools/steamvr_environments/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
11. [logs] 
```
okt 26 16:45:55 pop-os steam.desktop[6632]: 10/26 16:45:55 Init: Installing breakpad exception handler for appid(250820)/version(2.0.8)/tid(6632)
okt 26 16:45:55 pop-os steam.desktop[6386]: qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
okt 26 16:45:55 pop-os steam.desktop[6386]: qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
```
12. [logs] ../../third_party/tcmalloc/chromium/src/tcmalloc.cc:337] Attempt to free invalid pointer 0x55abd1c1a6a0
13. [logs] vrwebhelper[7069]: segfault at 39 ip 00007f6775603824 sp 00007ffcd2ac7800 error 6 in libcef.so[7f67754ec000+7770000] likely on CPU 4 (core 4, socket 0)
14. Bluetooth Error on SteamVR start.  On dismiss, Steam Client Update Required.
15. SteamVR cannot initialise for unknown reasons (Shared IPC Compositor Init Failed (303) (303))

Pop!_OS 22.04 LTS
SteamVR: 2.0.8 (Stable)
Steam: 1698260427
Steam-API-version:  SteamClient020
Gnome 42.9
Window system X11
32GB ram
AMD Radeon rx 6950 xt
Ryzen 7 7700x processor
Valve Index headset and controllers

**Comment by Beethoven-n** [comment]
might write a script to automate this workaround and make it easier since there's a set of commands to do already

**Comment by Beethoven-n** [comment]
yeah, doing that right now, will link to a gitlab when it's finished

**Comment by Beethoven-n** [comment]
https://gitlab.com/beethoven__/steam-workaround.sh
boop! done, should work. you need steamcmd for it to work, because that automates the download_depot commands

**Comment by Beethoven-n** [comment]
they... patched it?
`Steam>Depot download failed : missing license for depots 250823`

**Comment by Beethoven-n** [comment]
so you're not allowed to redownload the old version anymore. too bad, i already did! and archived it. just gonna use that from my system to force it to reinstall the old one lol

**Comment by vermeeren** [comment]
@Beethoven-n You might need to be logged in, so anonymous steamcmd possibly won't work properly. Haven't tested it.

**Comment by vsTerminus** [comment]
- **VR:** SteamVR 2.0.8 [beta]
- **Runtime:** Steam Linux Runtime 3.0 (sniper) [client_beta]
- **Steam:** Steam Client [beta]
- **OS:** Arch Linux [6.5.8-arch1-1]
- **Windowing System:** X11 [xorg-server 21.1.9-1]
- **Desktop Environment:** KDE/Plasma 5.29
- **CPU:** AMD Ryzen 9 5950X
- **GPU:** NVIDIA RTX 3090 Ti
- **GPU Driver:** nvidia-dkms 535.113.01-2
- **RAM:** 64GB DDR4
- **HMD:** Valve Index (+ 2 Knuckles + 2 Lighthouses)

As of 2.0.8 I was seeing the following behaviors:

- Shared IPC Compositor Init Failed (303) on launch
- A warning that I need to update my SteamVR Beta to get the latest features
- Games such as Ragnarock and Assetto Corsa Competizione will launch and the on-screen mirror works correctly and reflects the HMD's movement, but the lenses display only a black screen.
- Games such as Microsoft Flight Simulator 2020 which do not launch directly into a VR mode but launch in 2D and then switch into VR with a toggle do not see the headset and will not toggle
- Standalone games such as DCS World Standalone Version will open briefly and then SteamVR almost immediately crashes. Sometimes the process restarts cleanly, sometimes it causes my entire computer to lock up and require a reboot.
- Standalone apps like vr-video-player do not display anything on the lenses, they also show only black.

Following a comment I found here: https://bbs.archlinux.org/viewtopic.php?pid=2074266#p2074266 I moved my vrappconfig and steamvr.vrsettings file out to a temporary folder and restarted Steam. SteamVR launched with the same warnings as usual but this time I actually got picture in the HMD again, and I could launch Ragnarock and vr-video-player normally again.

DCS Standalone will launch with the old single-threaded executable (Which did not use OpenXR and talked to SteamVR directly), I can load into a plane and if I hold my head still everything is nice and smooth (40fps) but when I try to look around it gets laggy and jumpy impossible to use.

Launching the multi-threaded executable (which only works with OpenXR) results in SteamVR crashing at-or-before the main menu. The following error appears: `SteamVR failed initialization with error code VRInitError_IPC_CompositorInvalidConnectResponse: "Shared IPC Compositor Invalid Connect Response (307)" Please verify SteamVR is properly installed and try again"`

(I added it as a non-steam game shortcut in Steam, otherwise it launches in "VR mode" but nothing appears in the HMD if launched directly via Wine)

Overall it's mostly functional for me and most of my VR games seem to work, but DCS is either unplayable or crashes, and MSFS can't see the headset to refuses to even switch into VR mode.

**Comment by DASPRiD** [comment]
Running into the same issues on PopOS 22.04 with X11 and NVIDIA. VR does start and I can see the normal mountain background in the headset, but also getting error 303 and VR games just error out when trying to be started. Will try the rollback to 1.27 as mentioned above.

**Comment by vermeeren** [comment]
@DASPRiD I get the HMD not found error too but as you say it works anyway. VRChat works for me too, I use Proton-GE 8-16 (8-21 doesn't work for me). Myself I had to delete the wine prefix once to get it properly working after recent updates, perhaps that works for you too? See https://github.com/ValveSoftware/Proton/issues/1199#issuecomment-1759487894

**Comment by MalikuMane** [comment]
I'm seeing this same error on openSUSE Leap 15.5 but not noticing any symptoms from it. I can still play just fine.

**Comment by peterfab9845** [comment]
I notice this message in vrcompositor.txt:
```
Fri Oct 27 2023 03:37:19.494534 [Detail] - Processing Message of type VRMsg_CompositorConnect (108 bytes) from 
Fri Oct 27 2023 03:37:19.494572 [Info] - Incompatible version from client attempting to connect. Compositor: 55696 Client: 55056
Fri Oct 27 2023 03:37:19.494595 [Info] - External connection from /home/peter/.local/share/Steam/ubuntu12_32/steam 196395
Fri Oct 27 2023 03:37:19.494686 [Info] - Socket closed
Fri Oct 27 2023 03:37:19.494710 [Info] - Unable to read message from socket: 0
Fri Oct 27 2023 03:37:19.494731 [Info] - Process steam (196395) disconnected (Thread(0x0x7f79b00035b0/0x0x7f)
Fri Oct 27 2023 03:37:19.494745 [Info] - Lost pipe connection from steam (196395)
```
This is with SteamVR 2.0.8. Steam client version looks like 1698260427?
```
10/27 03:36:26 Init: Installing breakpad exception handler for appid(steam)/version(1698260427)/tid(196395)
```

**Comment by Korysovec** [comment]
Same error on Arch, works totally fine on Steam Deck though. Same version on both.

**Comment by megagtrwrath** [comment]
@Korysovec You say that it works perfectly fine on Steam Deck. Do you not get error 303? If so, does the new UI show?

**Comment by Korysovec** [comment]
@megagtrwrath Oh no, sorry for my misleading comment. I totally didn't realize that the UI didn't load. I just appeared in SteamVR home and launched some games from the wall. I cannot do the same on my desktop, where I am stuck on the loading screen and can't open nor see any games.

**Comment by megagtrwrath** [comment]
@Korysovec I can understand the reasoning for your comment, SteamVR does mostly function despite error 303 and the new UI not showing, it's just not optimal.

**Comment by TTimo** [comment]
This should be fixed in latest SteamVR beta (2.0.10)

**Comment by jarettmillard** [comment]
I was getting this in SteamVR 2.0.8, which was working okay apart from not showing the new UI. With 2.0.10 I'm getting this issue again and can't use SteamVR at all: https://github.com/ValveSoftware/SteamVR-for-Linux/issues/622

Using ALVR on Pop OS 22.04/Gnome/X11/Nvidia.

**Comment by megagtrwrath** [comment]
Issue is resolved, at least for me. New UI also seems to show so this may have been the root cause of #614 .

System Information (please complete the following information):

Distribution: Arch
SteamVR version: 2.0.10 (Beta)
Steam client version: 1698705032
Opted into Steam client beta?: Yes
Graphics driver version: 545.23.06
Gist for SteamVR System Information: https://gist.github.com/megagtrwrath/b4e6124fec30cd8dc95af43d958055e8

**Comment by ThaSwapMeetPimp** [comment]
Like jarretmillard, getting #622 on 2.0.10, and only #622 now (not throwing error 303 after error 497 but displaying in the headset). Moving to there.

**Comment by jarettmillard** [comment]
To be clear, I have nothing displaying in the headset.

**Comment by ThaSwapMeetPimp** [comment]
Yeah thats how it is for me like 75% of the time. Seems to be random, at least on my system.

**Comment by Korysovec** [comment]
@jarettmillard I've always had an issue getting ALVR to work with beta version of SteamVR. Perhaps we have to wait for a stable release.

**Comment by LiamDawe** [comment]
Also confirming I no longer get the problem, seems fixed in the latest Beta 2.0.10.

**Comment by Korysovec** [comment]
@jarettmillard Using [Steam-Play-None](https://github.com/Scrumplex/Steam-Play-None) I was able to get to the new UI using ALVR and SteamVR Beta 2.0.10. However games weren't able to start. I assume we will have to wait for full release anyways.

**Comment by Wemmy0** [comment]
Fixed as of Beta 2.0.10

**Comment by LordOfDragons** [comment]
Nothing is fixed at all. SteamVR still fails to run with that error and optionally crashes your entire PC in all recent versions. Please fix this. SteamVR on Linux is pretty much useless since over a year now !!!
